stages:
  - tests
  - report

default:
  services:
    - docker:24.0.5-dind

run_tests:
    stage: tests
    when: manual
    image: docker:24.0.5
    tags:
      - docker_dind
#    before_script:
#     - apk add curl
#     - ARTIFACTS_CHECK_URL="https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages&private_token=$PAT"
#     - curl -k --location --output artifacts.zip $ARTIFACTS_CHECK_URL
#     - unzip artifacts.zip
#     - chmod -R 777 public
#     - mkdir -p allure_results
#     - cp -r public/history allure_results
    script: 
        - docker compose up pytest_runner_chrome
    after_script:
        - docker compose up report
    artifacts:
      paths:
        - allure_report
      when: on_success
      expire_in: 10 days

pages:
    stage: report
    tags:
      - docker_dind
    needs:
      - run_tests
    script:
        - mkdir public 
        - cp -r allure_report/* public
    artifacts:
      when: on_success
      expire_in: never
      paths:
        - public