services:
#  pytest_runner:
#    image: ui # tests
#    build: .
#    volumes:
#      - .:/test_project
#    command: /bin/sh -c "pytest -v -m docker --alluredir=allure_results/"

  selenium_chrome:
    image: selenium/standalone-chrome
    container_name: selenium_server_chrome_works
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://selenium_chrome:4444" ]
      interval: 3s
      timeout: 10s
      retries: 5
    shm_size: 2g
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - '4444:4444'
      - '7900:7900'

  pytest_runner_chrome:
    build: .
    depends_on:
      selenium_chrome:
        condition: service_healthy
    image: alpine_ui
    container_name: pytest_runner_chrome_works
    # network_mode: service:selenium_chrome
    # network_mode: host
    command: pytest -v -m docker --reruns 3 --alluredir=allure_results/
    environment:
      PASSWORD: ${PASSWORD}
    volumes:
      - .:/test_project

#  report:
#    image: tests
#    build: .
#    volumes:
#      - .:/test_project
#    command: /bin/sh -c "allure generate allure_results --clean -o allure_report"